"""Mapping differences and portable reports."""

import html
from collections import Counter
from dataclasses import dataclass
from typing import TYPE_CHECKING

from plugin_rosetta.utils.io.atomic import atomic_write_text
from plugin_rosetta.utils.io.sssom import read_sssom_tsv

if TYPE_CHECKING:
    from pathlib import Path

    from plugin_rosetta.mapping.models.sssom import Mapping, MappingSet

MappingKey = tuple[str | None, str, str | None]


@dataclass(frozen=True)
class MappingChange:
    """One mapping whose non-key content changed."""

    before: Mapping
    after: Mapping


@dataclass(frozen=True)
class MappingDifference:
    """Added, removed, and changed mappings."""

    added: tuple[Mapping, ...]
    removed: tuple[Mapping, ...]
    changed: tuple[MappingChange, ...]


def diff_mapping_sets(base: MappingSet | None, head: MappingSet) -> MappingDifference:
    """Compare mapping sets by their SSSOM triple key."""
    base_by_key = {_mapping_key(mapping): mapping for mapping in (base.mappings or [])} if base else {}
    head_by_key = {_mapping_key(mapping): mapping for mapping in (head.mappings or [])}
    added = tuple(head_by_key[key] for key in head_by_key.keys() - base_by_key.keys())
    removed = tuple(base_by_key[key] for key in base_by_key.keys() - head_by_key.keys())
    changed = tuple(
        MappingChange(before=base_by_key[key], after=head_by_key[key])
        for key in base_by_key.keys() & head_by_key.keys()
        if base_by_key[key].model_dump() != head_by_key[key].model_dump()
    )
    return MappingDifference(
        added=tuple(sorted(added, key=_mapping_key)),
        removed=tuple(sorted(removed, key=_mapping_key)),
        changed=tuple(sorted(changed, key=lambda change: _mapping_key(change.after))),
    )


def predicate_counts(mapping_set: MappingSet) -> dict[str, int]:
    """Count mappings by predicate."""
    counts = Counter(mapping.predicate_id for mapping in (mapping_set.mappings or []))
    return dict(sorted(counts.items()))


def render_markdown(mapping_set: MappingSet, base: MappingSet | None = None) -> str:
    """Render a concise mapping report."""
    difference = diff_mapping_sets(base, mapping_set)
    lines = [
        f"# Mapping report: {mapping_set.mapping_set_id}",
        "",
        f"Mappings: {len(mapping_set.mappings or [])}",
        "",
        f"Added: {len(difference.added)}",
        "",
        f"Removed: {len(difference.removed)}",
        "",
        f"Changed: {len(difference.changed)}",
        "",
        "## Predicate counts",
        "",
        "| Predicate | Count |",
        "| --- | ---: |",
    ]
    lines.extend(
        f"| {_escape_markdown(predicate)} | {count} |" for predicate, count in predicate_counts(mapping_set).items()
    )
    return "\n".join(lines) + "\n"


def render_html(markdown: str) -> str:
    """Render the report subset of Markdown as standalone HTML."""
    rows: list[str] = []
    body: list[str] = []
    in_table = False
    for line in markdown.splitlines():
        if line.startswith("| ") and not line.startswith("| ---"):
            cells = [html.escape(cell.strip()) for cell in line.strip("|").split("|")]
            tag = "th" if not in_table else "td"
            rows.append("<tr>" + "".join(f"<{tag}>{cell}</{tag}>" for cell in cells) + "</tr>")
            in_table = True
        elif line.startswith("# "):
            body.append(f"<h1>{html.escape(line[2:])}</h1>")
        elif line.startswith("## "):
            body.append(f"<h2>{html.escape(line[3:])}</h2>")
        elif line and not line.startswith("| ---"):
            body.append(f"<p>{html.escape(line)}</p>")
    if rows:
        body.append("<table>" + "".join(rows) + "</table>")
    return "<!doctype html>\n<html><body>\n" + "\n".join(body) + "\n</body></html>\n"


def generate_mapping_page(source: Path, destination: Path) -> Path:
    """Generate a marked documentation page from an SSSOM artifact."""
    report = render_markdown(read_sssom_tsv(source))
    atomic_write_text(destination, "<!-- Generated by plugin-rosetta. -->\n\n" + report)
    return destination


def _mapping_key(mapping: Mapping) -> MappingKey:
    return mapping.subject_id, mapping.predicate_id, mapping.object_id


def _escape_markdown(value: object) -> str:
    return str(value).replace("|", "\\|")
